✨ feat: 이메일 인증 기능 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #10
Opened 2021-12-06 20:24 UTC by healtheefart

## 💻 작업 내역
- 이메일 인증 기능 구현
- 이메일 인증 기능 테스트
![image](https://user-images.githubusercontent.com/63666375/144915918-5d3852a7-276d-44fe-9d3c-883e9f26f32b.png)
## 🔎 PR 특이 사항
- controller 테스트 할 때 이메일 인증 코드가 안 맞는 상황에서 exception 이 NOT_MATCH_EMAIL_CODE 가 아닌 INTERNAL_SERVER_ERROR 로 반환되는데 왤까요...?
- email.properties 가 yaml 일 때에는 오류가 나고 properties 로 하면 원하는 기능을 합니다. 이유는 모르겠지만 properties로 하면 오류 나지 않는데 구태여 yaml 로 바꾸지 않아도 될 것 같아서 properties 로 생성했습니다.

2021-12-07 05:40 UTC, buri-1029 requested changes
이메일 인증 구현 짱짱!! 
코드도 깔꼼하고 좋네용 남은 작업도 파이팅!!

2021-12-07 05:40 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/GlobalExceptionHandler.java
> +		);
```suggestion
		ErrorResponse response = ErrorResponse.of(
			ex.getErrorCode()
		);
```
이렇게 수정하면 하정님이 원하는 예외 메세지로 나올 거에오!!

2021-12-07 05:40 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/dto/MemberCreateRequest.java
> +	private String profileImageUrl;
```suggestion
	@NotBlank
	private String email;
	
	@NotBlank
	private String nickname;
	
	@NotBlank
	private String password;
	
	@NotBlank
	private String address;
	
	@NotBlank
	private String contact;
	
	@NotBlank
	private String profileImageUrl;
```
필드마다 개행을 주면 깔끔하고 보기 쉬울 것 같아용!!

2021-12-07 05:40 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/dto/MemberCreateRequest.java
> +					 .password(this.password)
비밀번호 암호화해주세용 [참고 블로그](https://youngjinmo.github.io/2021/05/passwordencoder/)
```suggestion
					 .email(this.email)
					 .nickname(this.nickname)
					 .password(passwordEncoder.encode(this.password))
```

2021-12-08 06:18 UTC, buri-1029 requested changes
security 개발 하고 있는 부분은 완료안되었으니 `develop`으로 그 부분 제거하고 `merge`해주면 좋을 것 같아요!!

2021-12-08 06:18 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/config/SecurityConfig.java
> +			.passwordEncoder(getPasswordEncoder());
test 중이라면 해당 부분을 제거하고 올려야 머지할 때 충돌되지 않을 것 같아유!

2021-12-08 06:18 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/dto/MemberDetailResponse.java
> +
한 줄 개행 😅
```suggestion

```

2021-12-08 07:12 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/config/SecurityConfig.java
> +			.passwordEncoder(getPasswordEncoder());
넵 지당하신 말씀이어유!

2021-12-08 08:15 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/dto/MemberDetailResponse.java
> +
앗 미스테잌😋

2021-12-08 08:30 UTC, healtheefart commented
이메일 재전송 부분은 추가하고
시큐리티 부분과 주석 삭제해서 다시 푸시푸시👊👊했슈

머지하면 될까유?

2021-12-08 14:12 UTC, Kwonkyu reviewed
고생하셧씀다!! :+1:

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/domain/enums/UserType.java
> +	ROLE_USER,
ROLE_USER는 어떤 때 쓰는 권한인가요? 회원과 센터 모두 가지는 권한인가용?

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/email/EmailController.java
> +		return new ResponseEntity<>("인증코드 검증완료", HttpStatus.OK);
`ResponseEntity.ok()` 메서드로 200 응답을 생성할 수 있숩니다!

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +	private final Logger logger = LoggerFactory.getLogger(this.getClass());
Lombok의 `@Slf4j` 어노테이션으로 간편하게 구현할 수 있어요!

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +		msg += "<a href=\"#\" style=\"text-decoration: none; color: #434245;\" rel=\"noreferrer noopener\" target=\"_blank\">Need!t, Inc</a>";
문자열 concatenation 에는 스트링 빌더를 써보는 것도 괜찮을 것 같아유!

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +			throw new IllegalArgumentException();
새로운 예외를 던지기보다 예외 처리기에서 처리하는 건 어떨까요?

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +	}
이 부분 구현이 빠졋네용

2021-12-08 14:12 UTC, Kwonkyu commented on src/main/resources/email.properties
> +AdminMail.password=NEEDIT12
민감정보는 나중에 환경 변수로 빼는게 좋을 것 같네요

2021-12-08 14:12 UTC, Kwonkyu commented on src/test/java/com/prgrms/needit/PasswordEncoderTest.java
> +			() -> assertTrue(passwordEncoder.matches(rawPassword, encodedPassword))
패스워드 엔코더 자체는 스프링 시큐리티에서 제공하는 기능이라 제대로 동작하는지보다 비밀번호가 암호화되서 저장되는지를 확인하는 테스트가 더 좋을것같습니다!

2021-12-08 15:35 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/domain/enums/UserType.java
> +	ROLE_USER,
앗 이 부분은 ROLE_(역할)로 바꾸려다가 잘못 바꾼 것 같습니다! 수정해서 다시 push 해야겠네요ㅠㅠ

2021-12-08 16:13 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/email/EmailController.java
> +		return new ResponseEntity<>("인증코드 검증완료", HttpStatus.OK);
앗 블로그 보면서 했는데 수정을 못 했구먼유! 수정해서 다시 푸시푸시하겠삼

2021-12-08 16:14 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +	private final Logger logger = LoggerFactory.getLogger(this.getClass());
아 그럼 @Slf4j 어노테이션 사용하는 걸로 변경하겠슴다!

2021-12-08 16:15 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +	}
아 이 부분은 시큐리티 관련한 내용이었는데 잘못 push 됐어요! 빼고 다시 push 해보려구여!

2021-12-08 16:15 UTC, healtheefart commented on src/main/resources/email.properties
> +AdminMail.password=NEEDIT12
맞아요! todo가 하나 더 늘었네유!

2021-12-08 16:19 UTC, healtheefart commented on src/test/java/com/prgrms/needit/PasswordEncoderTest.java
> +			() -> assertTrue(passwordEncoder.matches(rawPassword, encodedPassword))
헉 이 부분도 올라간 줄 몰랐네요! 이 부분은 단순히 encode 됐는지 직접 확인하는 용도로 만들었는데 다시 빼서 push 해야겠어요
db에는 encode 된 걸로 잘 들어간 걸 확인했는데 나중에 test 만들 때 넣을 수 있으면 넣어보도록 하겠습니다! (아직 제가 맡은 부분 test는 안 만들었습니다!)

2021-12-08 16:38 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +			throw new IllegalArgumentException();
그렇게 된다면 이 부분은 예외 naming과 code를 어떻게 해야될까요?

2021-12-08 16:39 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +		msg += "<a href=\"#\" style=\"text-decoration: none; color: #434245;\" rel=\"noreferrer noopener\" target=\"_blank\">Need!t, Inc</a>";
오홍 그래도 될 것 같네요! 수정 후 push 하겠습니다! string builder가 성능이 좋다고 했던가요?

2021-12-08 16:51 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/email/EmailService.java
> +		msg += "<a href=\"#\" style=\"text-decoration: none; color: #434245;\" rel=\"noreferrer noopener\" target=\"_blank\">Need!t, Inc</a>";
```suggestion
		StringBuilder msg = new StringBuilder();
		msg.append(
			"<img width=\"120\" height=\"120\" style=\"margin-top: 0; margin-right: 0; margin-bottom: 32px; margin-left: 32px;\" src=\"https://user-images.githubusercontent.com/63666375/144910925-ba033238-f721-47ab-89c2-c4b027ef5479.png\" alt=\"\" loading=\"lazy\">");
		msg.append(
			"<h1 style=\"font-size: 30px; padding-right: 30px; padding-left: 30px;\">이메일 주소 확인</h1>");
		msg.append(
			"<p style=\"font-size: 17px; padding-right: 30px; padding-left: 30px;\">아래 확인 코드를 Need!t 가입 창이 있는 브라우저 창에 입력하세요.</p>");
		msg.append(
			"<div style=\"padding-right: 30px; padding-left: 30px; margin: 32px 0 40px;\"><table style=\"border-collapse: collapse; border: 0; background-color: #F4F4F4; height: 70px; table-layout: fixed; word-wrap: break-word; border-radius: 6px;\"><tbody><tr><td style=\"text-align: center; vertical-align: middle; font-size: 30px;\">");
		msg.append(code);
		msg.append("</td></tr></tbody></table></div>");
		msg.append(
			"<a href=\"#\" style=\"text-decoration: none; color: #434245;\" rel=\"noreferrer noopener\" target=\"_blank\">Need!t, Inc</a>");

		message.setText(msg.toString(), "utf-8", "html"); //내용
		message.setFrom(new InternetAddress("needit.mailg@gmail.com", "needit")); //보내는 사람
```

2021-12-08 18:59 UTC, healtheefart commented
conflict 해결한 부분 확인하시고 [slack 스레드](https://greppkdt-webdev.slack.com/archives/C02NBKRPC1Y/p1638989746004700)나 여기에 comment로 확인했다고 메세지 남겨주세요!

2021-12-08 19:15 UTC, buri-1029 approved these changes
디비 컬럼명과 엔티티 필드명하고 맞추시고 머지하면 될 것 같아요!

2021-12-08 19:15 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/entity/Member.java
```suggestion
	private UserType userRole;
```

2021-12-09 05:33 UTC, merged