✨ feat : 센터 관리
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #13
Opened 2021-12-09 07:01 UTC by healtheefart

## 💻 작업 내역

- 회원 관리와 동일하게 센터 관리 부분 작업

## ❗ 변경사항

- Member 부분에서 EmailService 제거 (Email 부분은 common package에)
- BaseEntity 부분이 path가 달라서 common/entity/BaseEntity.class 로 통일
- ErrorCode
  - 공통 부분 : G###
  - Center 부분 : C###

## 🔎 PR 특이 사항 

- 스웨거로 테스트 했습니다!

2021-12-09 07:52 UTC, buri-1029 requested changes
언급한 부분만 수정해주시면 될 것 같아요! 하정님😆
열심히 하는 모습 보기 좋아유 ❤️🌈

2021-12-09 07:52 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/dto/CenterDetailResponse.java
> +	@NotBlank
Response에서는 해당 validation annotation를 제거해도 될 것 같아요!!

2021-12-09 07:52 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +}
```suggestion
	@Transactional
	public Long updateCenter(Long centerId, CenterUpdateRequest request) {
		Center activeCenter = findActiveCenter(centerId);
		activeCenter.changeCenterInfo(
			request.getEmail(),
			passwordEncoder.encode(request.getPassword()),
			request.getName(),
			request.getContact(),
			request.getAddress(),
			request.getProfileImageUrl(),
			request.getOwner()
		);
		return activeCenter.getId();
	}

	@Transactional
	public void deleteCenter(Long centerId) {
		Center activeCenter = findActiveCenter(centerId);
		activeCenter.deleteEntity();
	}
	
	@Transactional(readOnly = true)
	public Center findActiveCenter(Long centerId) {
		return centerRepository
			.findByIdAndIsDeletedFalse(centerId)
			.orElseThrow(
				() -> new NotFoundCenterException(ErrorCode.NOT_FOUND_CENTER));
	}
}
```
공통으로 사용하는 메서드는 맨 아래에 위치시켜주는 게 더 보기 좋을 것 같고 삭제되지 않은 센터를 찾아야하니 쿼리문 위 처럼 수정해주세용

2021-12-09 07:52 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +				() -> new NotFoundCenterException(ErrorCode.NOT_FOUND_CENTER));
```suggestion
		return new CenterDetailResponse(findActiveCenter(centerId));
```

findActiveCenter 메서드와 같은 역할을 하니 코드를 위와 같이 수정할 수 있겠네용!

2021-12-09 08:18 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/dto/CenterDetailResponse.java
> +	@NotBlank
네!네! 선생님!

2021-12-09 15:49 UTC, Kwonkyu reviewed
오홍홍 조와용~

2021-12-09 15:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +		@RequestBody CenterCreateRequest request
`@Valid` 어노테이션을 붙여서 validation을 적용해주면 더 좋을 것 같아요!

2021-12-09 15:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +	public Center findActiveCenter(Long centerId) {
이쪽에서는 엔티티 객체를, 위의 메서드에서는 response 객체를 반환하도록 구현한 이유가 궁금합니다!

2021-12-09 15:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/member/controller/MemberController.java
>  		@RequestBody MemberCreateRequest request
이쪽에도 validation 적용!

2021-12-09 20:11 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +}
아 공통으로 사용하는 메서드는 아래에 위치하는 게 더 보기 좋은 거였군요! 공통인 부분은 다 위로 올렸던 거 같은데 하나 배워갑니당!
말씀 주신 부분 수정하겠슴다~

2021-12-09 20:11 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +				() -> new NotFoundCenterException(ErrorCode.NOT_FOUND_CENTER));
앗 여기 있었네

2021-12-09 20:14 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +		@RequestBody CenterCreateRequest request
아하 RequestBody 부분에는 다 @Valid 를 쓰는 것이 좋나요? 하나 또 배워갑니당! 수정할게유~

2021-12-09 20:16 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +	public Center findActiveCenter(Long centerId) {
앗 이 부분 수정해서 올릴게요! findActive 메서드를 제가 사용을 하지 않았어요!

2021-12-09 20:16 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/controller/MemberController.java
>  		@RequestBody MemberCreateRequest request
넵 수정수정~

2021-12-09 20:44 UTC, healtheefart commented
수정했슈~ 
본인이 본인 정보 조회할 때는 MemberDetailResponse, CenterDetailResponse,
타인 정보 조회할 때는 MemberResponse, CenterResponse로 했는데
naming을 바꾸는 게 나을까요?
(예 : 본인 정보 조회할 때는 MemberSelfResponse, 타인 정보 조회할 때는 OtherMemberResponse ?)

2021-12-10 08:36 UTC, healtheefart commented
<기능 추가>
- email, nickname 중복검사 api 추가

<수정>
- (리뷰 반영한 부분) entityCreateRequest, entityUpdateRequest -> entityRequest로 통합 
- (리뷰 반영한 부분) MemberDetailResponse -> MemberSelfResponse
- (리뷰 반영한 부분) Email package 이동
- IsUniqueResponse getter 제거
- Email request 받는 부분 Map -> EmailDto
- Email 전송 시 발생하는 예외 handler 구현

Member의 email, nickname & Center의 email, name 중복검사는 부리님이 만드신 user 부분 pull 받고 난 후에 수정하고 merge

2021-12-11 10:25 UTC, buri-1029 requested changes
코드리뷰 했습니당 확인해주세용 뿅 ❤️🌈 (좀 많아져버렸네용...하하 죄송함다ㅠ)

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_FOUND_CENTER(404, "C001", "존재하지 않는 회원입니다."),
```suggestion
	NOT_FOUND_CENTER(404, "C001", "존재하지 않는 센터입니다."),
```

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +	}
이부분은 센터와 회원 둘다 검사할 수 있는 api인가요? 그러면 공통인 UserController 로 두는 게 좋을 것 같아요!

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/dto/CenterSelfResponse.java
> +	private String password;
저희 password는 암호화된 정보로 응답해 버려서 빼기로 하지 않았나요? 아니면 정보 다보내주고 프론트쪽에서 password 안보이도록 해야할 것 같아요!!

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +	}
```suggestion
	@Transactional(readOnly = true)
	public IsUniqueResponse checkEmailIsUnique(String email) {
		return new IsUniqueResponse(!centerRepository.existsByEmail(email));
	}

	@Transactional(readOnly = true)
	public IsUniqueResponse checkNameIsUnique(String name) {
		return new IsUniqueResponse(!centerRepository.existsByName(name));
	}
```

앞에 ! 는 무슨 의미인가요?

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
>  		// 저장된 emailCode와 맞는지 확인
주석 제거!!!

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +	}
```suggestion
	@Transactional(readOnly = true)
	public IsUniqueResponse checkEmailIsUnique(String email) {
		return new IsUniqueResponse(!memberRepository.existsByEmail(email));
	}

	@Transactional(readOnly = true)
	public IsUniqueResponse checkNicknameIsUnique(String nickname) {
		return new IsUniqueResponse(!memberRepository.existsByNickname(nickname));
	}
```

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +				() -> new NotFoundMemberException(ErrorCode.NOT_FOUND_MEMBER));
예외를 기존 `NotFoundMemberException`은 지우고 있는 `NotFoundResourceException` 이 예외를 사용해서 에러코드로만 어떤 리소스(현재는 멤버)가 존재하지 않는지 확인해도 될것같은데 하정님 생각은 어떠신가용?

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/email/controller/EmailController.java
> +	}
주석 제거!!

2021-12-11 10:25 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/entity/Center.java
> +		this.userRole = UserType.ROLE_CENTER;
머지 후 
```suggestion
		this.userRole = UserType.CENTER;
```
로 변경해주세용!

2021-12-11 10:37 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +	}
넵넵 그래서 email, name/nickname 확인하는 부분은 develop에 merge하고 다시 시작하려구여!!

2021-12-11 10:38 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/dto/CenterSelfResponse.java
> +	private String password;
아 그랬군여!! 그럼 response에서 password 제거하겠슴다!!

2021-12-11 10:40 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/service/CenterService.java
> +	}
아 유니크한 값이면 exist 하면 false, not exist하면 true 로 반환하기 위해서 추가했어요! 
email, name/nickname check하는 부분은 아무래도 헷갈리니... 제거하고 develop 머지한 후에 다시 시작하는 게 낫겠네요!! 혼란스럽게 해서 죄송해유~

2021-12-11 10:41 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
>  		// 저장된 emailCode와 맞는지 확인
앗차!

2021-12-11 10:42 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +	}
오홍 어노테이션 추가하겠슴다!! 많이 배워가유♥

2021-12-11 10:47 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +				() -> new NotFoundMemberException(ErrorCode.NOT_FOUND_MEMBER));
사실 예외가 하나밖에 없는 부분들은 공통 exeption을 사용하는 쪽으로 가야겠다 싶었는데 NotFoundResourceException 있었군요! 예외부분을 다시 살펴보니 NotFound, NotMatch 부분이 같이 사용되는 게 많은 것 같은데 NotMatch 부분도 NotMatchResourceException으로 합치는 게 어떨까요??

2021-12-11 10:48 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/controller/EmailController.java
> +	}
하잇!

2021-12-11 10:48 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/entity/Center.java
> +		this.userRole = UserType.ROLE_CENTER;
에구머니나! 수정하겠습니다!

2021-12-11 11:06 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_FOUND_CENTER(404, "C001", "존재하지 않는 회원입니다."),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-12-11 11:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +		@RequestBody CenterCreateRequest request
입력값을 검증하는 부분에 쓰면 좋아요! 사용자 입력값을 받는 컨트롤러 단에서 특히 유용

2021-12-11 12:22 UTC, Kwonkyu approved these changes
굿굿~!

2021-12-11 12:22 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/enums/UserType.java
> +	private String type;
key 랑 type은 무슨 역할이에유?

2021-12-11 12:22 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +	public ResponseEntity<Void> deleteCenter() {
나중에 path variable 넣어둡시다!

2021-12-11 12:22 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +		log.info("보내는 대상 : " + receiver);
concatenation 대신 템플릿으로 하면 좋을것같아요!

2021-12-11 16:58 UTC, healtheefart commented on src/main/java/com/prgrms/needit/common/enums/UserType.java
> +	private String type;
UserType 이 부분은 제가 수정하지 않아서 잘 모르겠습니다! @buri-1029 부리님? key와 type은 무슨 역할인가여?

2021-12-11 17:01 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +	public ResponseEntity<Void> deleteCenter() {
시큐리티 적용하면 center, member controller에서 path variable은 빼기로 해서 일단은 넣지 않고 특정 아이디를 사용하는 식으로 짰어요!

2021-12-11 17:03 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +		log.info("보내는 대상 : " + receiver);
넵 수정하겠습니다!

2021-12-11 18:05 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/member/service/MemberService.java
> +				() -> new NotFoundMemberException(ErrorCode.NOT_FOUND_MEMBER));
엇 그렇게 하는 것이 커스텀예외도 많이 추가되지 않으니 좋은 방법이네요!! 저도 그렇게 수정할게용!!

2021-12-11 18:08 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/center/controller/CenterController.java
> +	}
아항 그렇군용!! 좋아용😆

2021-12-11 18:10 UTC, buri-1029 approved these changes

2021-12-11 18:54 UTC, merged