NEED-94 알림 기능 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #14
Opened 2021-12-09 08:47 UTC by Kwonkyu

**실시간 알림이 아닙니다!**

알림 기능은 새로운 게시글 등록, 작성한 게시글에 달린 새로운 댓글 등 사용자가 인지해야 하는 내용을 저장하고 제공하기 위한 기능입니다. STOMP에서 특정 사용자에게 웹 소켓을 이용하여 실시간 알림을 보낼 때 API, JWT 환경에서는 설정이 좀 더 필요하기 때문에 별도의 백로그로 구축할 예정입니다.

알림을 생성하려면 알림을 생성하는 기능(게시글 작성, 댓글 작성 서비스 등)에서 알림 서비스를 사용해야 하기 때문에 현재는 기본적인 알림 조회 및 생성 기능만 구현했습니다.

기존의 기능과 분리하여 알림을 전달하는 기능 자체를 핸들러 인터셉터로 구현하여 관점을 분리하는 방안은 멘토님과 상의 후 고려해보겠습니다.

2021-12-09 16:15 UTC, buri-1029 requested changes
권규님 고뇌하는 모습이던데.... 알림 기능 하느라 수고하십니당ㅠㅠ

저는 아직 메서드나 필드명을 길게 정하는 걸 좋아하지 않는데 권규님 코드를 보니 각각 무슨 역할인지 명확하게 알 수 있어서 좋긴하네용

2021-12-09 16:15 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private Long notifiedUserId;
Notification 도메인 안에 있는 필드이니 
```suggestion
	private Long userId;
```
로 해도 좋을 것 같아요!

2021-12-09 16:15 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/repository/NotificationRepository.java
> +public interface NotificationRepository extends PagingAndSortingRepository<Notification, Long> {
JpaRepository와 무슨 차이가 있나요??

2021-12-09 16:15 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +	}
저는 위 두 메서드(`createAndSendMemberNotification`, `createAndSendCenterNotification`)만 있거나 이 메서드 하나(`createAndSendNotification`)만 있을면 될 것 같다고 생각하는데용 권규님은 어떻게 생각하시나용?

2021-12-09 16:15 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +	}
`NotificationService` 에서 알림을 저장하는 로직을 미리 작성해놓고 다른 도메인에서 알림가도록 하고 싶다면 해당 서비스를 주입받아서 사용하면 되겠군요!!

2021-12-11 09:41 UTC, healtheefart reviewed
권규님 고생하셨슈😀 
권규님 pr에 리뷰 달다가 네이밍 보고 웃겨서 침 나왔어요ㅋㅋㅋㅋ
알림이 notification이라서 관련 네이밍들이 다 길긴 기네욬ㅋㅋㅋㅋ
앞으로 남은 개발까지 파이팅~🦾

2021-12-11 09:41 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +		return notificationRepository.findAllByNotifiedUserIdAndNotifiedUserTypeAndCheckedFalse(
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ개웃곀ㅋㅋㅋㅋㅋ
엇 근데 마지막에 IsCheckedFalse 아닌가여??

2021-12-11 09:41 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private Long notifiedContentValue;
notifiedContentValue 는 어떤 정보인건가요?

2021-12-11 11:05 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private Long notifiedContentValue;
아 이거는 만약에 센터가 게시글을 올렸다! 하면 게시글 번호같은걸 담으려구 넣어놨어요. 그래서 프론트엔드에서 클릭하면 해당 게시글로 이동하는 링크를 만들 수 있도록 하려구용

2021-12-11 11:07 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +		return notificationRepository.findAllByNotifiedUserIdAndNotifiedUserTypeAndCheckedFalse(
쿼리 메서드는 `Checked` 라고 인식하더라구용! 아무래도 불리언 필드는 `checked` 처럼 쓰고 메서드에서 `isChecked` 로 네이밍하는 경우가 많아서 그런지 JPA 에서 자동으로 인식하는듯 합니더 😁

2021-12-11 11:08 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +	}
앗 맞아용! 그래서 다른 기능들이 개발된 후에 적용해야 될 것 같더라구요 ㅠㅠ

2021-12-11 11:33 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +	}
후자가 괜찮은 것 같네요! 편의를 위해서 만들어 둔 거긴 한데.. 그렇게 효과는 없을것같아요 😂

2021-12-11 11:42 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/repository/NotificationRepository.java
> +public interface NotificationRepository extends PagingAndSortingRepository<Notification, Long> {
`JpaRepository` 에는 `flush` 나 배치 작업같은 추가적인 기능이 있다구 하네용! 저는 `CrudRepository`나 `PagingAndSortingRepository`로 쓰던게 습관이라 이렇게 했어요

2021-12-11 11:42 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private Long notifiedUserId;
넵!

2021-12-11 18:13 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +		return notificationRepository.findAllByNotifiedUserIdAndNotifiedUserTypeAndCheckedFalse(
오오 그러면 deleted 관련 부분도 IsDeleted 가 아닌 Deleted 로 해도 인식하겠군요!!

2021-12-11 18:16 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/entity/response/NotificationResponse.java
> +	private final boolean isChecked;
필드명과 같은 이름으로 응답해주면 `@JsonProperty` 부분을 제거해도 될 것 같은데 권규님의 생각은?!!???!

2021-12-11 18:17 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private String previewMessage;
요건 어떤 역할을 하기 위한 필드인가용???

2021-12-11 18:19 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/service/NotificationService.java
> +	}
오호잇...! 빨리 구현하도록 하겠숨다!!

2021-12-11 18:20 UTC, buri-1029 approved these changes

2021-12-12 06:11 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/entity/response/NotificationResponse.java
> +	private final boolean isChecked;
아 이거는 저희가 코딩하다가 리팩토링같은걸 하면서 필드명을 바꿨을 때 그게 프론트엔드까지 직접적으로 영향을 끼치지 않도록 네이밍을 고정시켜뒀어요! 하지만 프론트엔드 분들이 스웨거를 자주 확인하시면서 계속 업데이트해주신다면 필요없는 부분이 되겠네용!😀

2021-12-12 06:17 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private String previewMessage;
이거는 알림 메시지의 미리보기? 같은 느낌이에요. 예를 들어 센터가 "담요 20장이 필요합니다." 라는 제목의 게시글을 올렸을 때 사용자가 로그인해서 알림 목록을 확인하면 "관심 센터에서 게시글을 올렸습니다. '담요 20장이 필요합니다...'" 처럼 보여주려구요!

2021-12-12 06:21 UTC, merged

2021-12-12 12:59 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/entity/Notification.java
> +	private String previewMessage;
그 부분은 기본 메시지를 프론트가 처리하면 될 것 같아여...!!