feat: NEED-171 본인과 관련된 기부 예약 목록을 확인할 수 있는 API 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #18
Opened 2021-12-13 07:55 UTC by Kwonkyu

# 개발 내역
요구사항에서 놓친 부분이 있어서 해당 기능을 개발하고 시큐리티를 적용했습니다.

2021-12-13 13:58 UTC, buri-1029 requested changes
고생하셨어요!! 피드백 확인해주세욤!!

2021-12-13 13:58 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/controller/NotificationController.java
> +			.getUncheckedNotifications(userService.getCurUserId(), userService.getCurUserType());
현재 로그인한 유저는 서비스에서 사용해도 될 것 같아요!

2021-12-13 13:58 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/login/service/UserService.java
> +
권규님 각 도메인 서비스에서 getCurCenter랑 getCurMember 메서드 선언한 다음 null이 아닌 객체의 아이디와 타입을 사용하도록 제가 구현해놓았는데요..... 음... 네...

2021-12-13 13:58 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	INVALID_STATUS_CHANGE(400, "D008", "허가되지 않은 거래상태 변경입니다."),
INVALID_STATUS_VALUE(400, "D005", "잘못된 거래상태 타입입니다."), 이 에러와 같은 것 같은데요...? 다른 건가요...?

2021-12-13 16:54 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/login/service/UserService.java
> +
아 이건 제가 사용하려고 만든 메서든데 지우고 사용하는 서비스에서만 별도로 메서드로 정의해서 쓰는 방식으로 할까용?

2021-12-13 16:55 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	INVALID_STATUS_CHANGE(400, "D008", "허가되지 않은 거래상태 변경입니다."),
전자는 거래상태 enum 값 파싱 상황에서, 후자는 거래상태를 변경할 때 권한이 없으면 발생하는 예외로 정의해 둔 것 같네요!

2021-12-13 17:10 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	INVALID_STATUS_CHANGE(400, "D008", "허가되지 않은 거래상태 변경입니다."),
권한은 어떤 권한인가요? 거래상태 변경할때 해당 유저에 접근 권한에 대해서는 다른 예외가 발생하거든요!

2021-12-13 17:11 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/login/service/UserService.java
> +
음 넹🤔 그러는 게 나을 것 같아요!!

2021-12-13 17:23 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/controller/NotificationController.java
> +			.getUncheckedNotifications(userService.getCurUserId(), userService.getCurUserType());
아 이거는 다른 브랜치에서 반영했어가지구 이쪽에선 깜박했네용

2021-12-13 17:23 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	INVALID_STATUS_CHANGE(400, "D008", "허가되지 않은 거래상태 변경입니다."),
무슨 예외가 발생하나요??

2021-12-14 04:46 UTC, buri-1029 approved these changes
제가 피드백한 부분만 확인해주세용 일단 승인할게용

2021-12-14 04:46 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
이 부분 service에도 있던데 삭제해도 되지 않을까요? 현재 로그인한 유저에 대해서는 service에서 구현해도 될 것 같아요!
즉 userService를 담당한 도메인 서비스에 주입받는 식으로요!! 그리고 제가 userService에 공통으로 사용할 수 있는 getCurUser 메서드 구현했는데 요걸 사용하면 코드가 더 간결해질 것 같아요 :)

제 PR 에서 userService 확인

2021-12-14 04:46 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/controller/NotificationController.java
> +	}
여기도 마찬가지!

2021-12-14 05:28 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
아 이 브랜치에는 아직 반영이 안되서요! 그 userService 에 기능 등록된 PR 머지되면 반영할게요!

2021-12-14 05:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/notification/controller/NotificationController.java
> +	}
넵!

2021-12-14 06:08 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
엇 그부분이 아니라 해당 메서드를 쓰는 걸 서비스에서 하면 될 것 같아서용 해당 컨트롤러에 getCurUserType() 이걸 사용하는 부분을 서비스에서 하고 컨트롤러에서는 그 필드를 제거하는거죠!!

2021-12-14 06:45 UTC, healtheefart approved these changes
수과셨슴다~! 이번 주도 미리 수고수고!! 겁나 빡세게 달려보아용!!

2021-12-14 06:45 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
>  			default:
BoardType을 수정해서 swith 분기문을 없애고 코드를 줄일 수 있을 거 같아용!

2021-12-14 16:33 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
>  			default:
switch를 없애면 서비스 안으로 옮겨져가지고.. 리팩토링할 때 고려해보겠습니당~

2021-12-14 16:33 UTC, merged

2021-12-14 17:29 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/service/ContractService.java
> +	}
이부분을 UserType enum에 넣으면 더 깔끔할 것 같아요!

2021-12-14 17:37 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/notification/controller/NotificationController.java
> +			.getUncheckedNotifications(curUser.getId(), UserType.valueOf(curUser.getRole()));
해당 로직을 서비스에서 구현하지 않은 이유가 있을까용?