✨ feat: NEED-167 WebSocket을 이용한 채팅 기능 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #33
Opened 2021-12-16 16:03 UTC by Kwonkyu

# 구현 기능
- 웹 소켓을 이용하여 채팅 메시지 전달 시 기존 채팅 메시지 전달 기능과 알림 생성 기능을 활용하도록 구현.
- 프론트엔드와 상의를 통한 API 응답값 조정.

2021-12-16 16:16 UTC, buri-1029 requested changes
오오 채팅 기능까지.... 수고하십니당👍👍👍

2021-12-16 16:16 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/controller/RealtimeChatBroker.java
> +		Principal principal
`Principal` 를 사용하신 이유가 뭔가요? 현재 사용자를 반환하기 위해서인가요? 그럼 userService에 있는걸 사용하면 되지 않을까요? 단순히 현재 로그인한 사용자의 이메일만 갖고오기 위함이군요

2021-12-16 16:16 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/entity/response/ChatUserResponse.java
> +	public ChatUserResponse(Member member) {
저는 분류해줘서 생성해야하는 부분을 기본 생성자는 private으로 하고 정적 팩토리 메서드로
`public static ChatUserResponse toResponse(Member member)` 이런식으러 했는데 어떻게 생각하시나용

2021-12-16 16:22 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/controller/RealtimeChatBroker.java
> +		Principal principal
스프링의 메시지 핸들러에서 지원하는 파라미터기 때문에 사용했습니다! 현재 로그인한 사용자의 이메일이 username이기 때문에 이걸 바로 불러올 수 있도록 사용했네요.

2021-12-16 16:24 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/entity/response/ChatUserResponse.java
> +	public ChatUserResponse(Member member) {
나쁘지 않은 방법인 것 같네요

2021-12-17 05:29 UTC, healtheefart approved these changes
수과셨슴다!! 오늘도 파이팅이어요!! 빠샤빠샤!!

2021-12-17 05:29 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/message/entity/response/ChatMessageResponse.java
>  			null :
오호라 if 문을 이렇게 줄이셨네요? 굿굿!

2021-12-17 06:16 UTC, buri-1029 approved these changes

2021-12-17 06:20 UTC, merged