✨ feat : 공공 API 연동
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #37
Opened 2021-12-17 13:13 UTC by healtheefart

## 💻 작업 내역

- (OpenApiController/Service) openApi 연동
- Request/Response Dto 추가
  - (BusinessRequest) 입력받는 request
  - (BusinessesRequest) open api 요청 형식에 맞춘 request
  - (BusinessRawResponse) open api에서 전달받는 response
  - (BusinessRefinedResponse) BusinessRawResponse 를 정제한 response dto
- OpenApiException 추가

## ❗ 변경사항

- (공통부분) SecurityConfig 사업자등록번호 조회 url("/call-api") 허용

## 🔎 PR 특이 사항 

- 공공api가 request 형식과 response 형식이 정해져 있어서 불가피하게 dto가 조금 많아졌습니다
- open api 기능에서 나오는 예외가 하나는 서버 연결 예외, 하나는 parsing 예외(형식에 맞지 않게 건네줬을 때)인 것 같은데 일단 서버 연결 예외 하나만 추가했습니다 (+ 상의 후 후자도 추가 예정)

2021-12-17 18:20 UTC, buri-1029 requested changes
피드백 남긴 부분만 확인해주시면 될 것 같아요! 코드 깔끔하네영😆👍

2021-12-17 18:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRawResponse.java
> +	@JsonProperty("data")
저는 받는 필드명을 다르게 해주고 싶다면 해당 어노테이션을 사용하는 것으로 알고 있는데요! json으로 보여줄 부분이랑 필드명이 같다면 `@JsonProperty()` 어노테이션은 삭제해도 괜찮을 것 같아요! [참고](https://velog.io/@ctp102/SpringBoot-JsonNaming-JsonProperty%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

2021-12-17 18:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRefinedResponse.java
> +@Getter
```suggestion
@Getter
@NoArgsConstructor
```

2021-12-17 18:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRequest.java
> +	private String p_nm;
어노테이션이 적용되어있다면 개행으로 보기좋게 해주거나 아니면 여기도 응답 필드명이 같으니 해당 어노테이션을 안사용해도 될 것 같아요!

2021-12-17 18:29 UTC, Kwonkyu approved these changes
LGTM~

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/email/controller/EmailController.java
>  	public ResponseEntity<String> verifyCode(
ApiResponse 로 감싸지 않도록 프론트랑 협의가 된 부분인가유?

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/controller/OpenApiController.java
> +	public ApiResponse<BusinessRefinedResponse> checkBusinesscode(
이쪽에는 ResponseEntity 가 빠졌네요? 어차피 OK 라 필요 없어서 그런건가유?

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRawResponse.java
> +		private Request_param request_param;
카멜 케이스로 하는것도 괜찮을 것 같습니다!

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRefinedResponse.java
> +	@JsonProperty("valid_msg")
프론트 응답값도 카멜 케이스로 통일하는건 어떨까요?

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRequest.java
> +	private String p_nm;
`@NotBlank` 같은 validation 을 적용하는 것도 괜찮을 것 같습니다!

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessesRequest.java
> +	private List<BusinessRequest> businesses;
이 리스트의 목적은 무엇인가요?

2021-12-17 18:29 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/openAPI/service/OpenApiService.java
> +			wr.flush();
공공 API 서버에 요청을 보내는 부분인가요? 스프링에서는 비슷한 목적으로 `RestTemplate` 이란 걸 제공하더라구요. 나중에 한 번 확인해보셔도 괜찮을 것 같습니다!

2021-12-18 19:30 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRawResponse.java
> +	@JsonProperty("data")
아하...!! intellij plugin으로 자동 완성시킨 클래스였는데 완성시키고 제대로 알아보지 않았습니다ㅠㅠ
변수명을 좀 더 명시적으로 바꾸고 관련 dto 중에서 해당 어노테이션을 사용하지 않아도 되는 부분에는 제거하도록 할게요...!! 감삽니다!!

2021-12-18 19:33 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRequest.java
> +	private String p_nm;
@buri-1029 @Kwonkyu 수정하도록 하겠습니다! 제가 기본적인 걸 자꾸 빼먹네여ㅠㅠ

2021-12-18 19:34 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/controller/EmailController.java
>  	public ResponseEntity<String> verifyCode(
아이코... 아니요ㅠㅠ 이 부분 왜 api response로 안 감싸졌을까요... 수정하고 다른 부분에서도 실수한 건 없는지 전체적으로 확인해보겠습니다...!!

2021-12-18 19:46 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/controller/OpenApiController.java
> +	public ApiResponse<BusinessRefinedResponse> checkBusinesscode(
깊게는 생각 안 하고 data 안에 status_code라는 게 있어서 중복되는 것 같기에 responseEntity는 뺐어요...!
혹시 responseEntity를 사용해서 우리 서버의 문제인지, 공공api 서버의 문제인지 구분할 수 있을까요?

2021-12-18 19:46 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRawResponse.java
> +		private Request_param request_param;
넵 변수명을 좀더 명시적으로 수정하겠습니다!

2021-12-18 19:46 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRefinedResponse.java
> +	@JsonProperty("valid_msg")
넵넵!

2021-12-18 19:48 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessesRequest.java
> +	private List<BusinessRequest> businesses;
공공api가 한번에 여러개의 요청을 보내는 식으로 짜여진 구조라서 request를 리스트로 받더라고요...! 그래서 사용자에게 받아온 request를 공공api request에 맞게 원소가 하나인 list로 바꿔서 보내줬습니다

2021-12-18 20:02 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/openAPI/service/OpenApiService.java
> +			wr.flush();
HttpURLConnection 대신에 사용할 수 있는건가요...? 오홍... 조사해보고 좀 더 좋은 방식이라면 수정해보고 나중에 이슈정리할 때 정리해놓겠습니다..!!

2021-12-19 03:02 UTC, Kwonkyu approved these changes
굿!~

2021-12-19 05:22 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/openAPI/dto/BusinessRawResponse.java
> +		private Request_param request_param;
변수명은 응답으로는 괜찮은데 객체명은 카멜로 하는 게 좋겠네요!

2021-12-19 05:43 UTC, merged