✨ feat : Redis를 통한 이메일 인증코드 만료처리기능 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #64
Opened 2022-01-06 21:14 UTC by healtheefart

## #55 Redis를 통한 이메일 인증코드 만료처리기능 구현
- 만료시간 3분(180000ms)
- key : value = code : email

2022-01-07 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/util/RedisUtil.java
> +public class RedisUtil {
RedisUtil로 따로 빼서 관리하였군요! 하정님 코드 사용해야겠어용

2022-01-07 04:24 UTC, buri-1029 approved these changes
하정님 일단 레디스 서버는 도커로 관리하고 계신 건 가요? 제가 EC2로 관리하면 하나로 합치기로 합시당

2022-01-07 04:24 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/util/RedisUtil.java
> +public class RedisUtil {
오홍 RedisUtil로 따로 빼서 관리했네요! 하정님 코드 활용해야겠슴다

2022-01-07 05:34 UTC, Kwonkyu approved these changes
오호 레디스 템플릿이란게 있었군요!! 👍

2022-01-07 05:34 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +
이 쪽에서는 IDE에서 조언 뜨지 않나요?

2022-01-07 18:16 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +
엇 그러네요!

2022-01-08 04:36 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +
예에에전에 스트링 버퍼랑 스트링 빌더랑 비교할 때 동기화 때문에 성능 차이가 있다더라구여. 이거 키 생성하는 부분은 static으로 둔 이유가 있나용

2022-01-10 19:58 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +
이메일 인증 부분은 구글링으로 자료들을 참고했는데요!
참고했던 코드에서 util성 메서드라고 생각한 것인지 아님 한번 생성된 code를 변경없이 사용하려고 해서인지 static 메서드로 둔 것 같아요
근데 지금 확인해보니 재사용하는 부분이 없고, 재사용해서 사용하려니 static final 메서드로 둬야 변경없이 사용이 되네요!
수정하고 push할테니 수정한 부분으로 다시 확인해주세요!

2022-01-20 16:54 UTC, healtheefart commented
redis 사용 부분을 통일하려고 EmailService에서만 사용하던 RedisService 삭제하고 emailService 변경했습니다!

2022-01-21 07:20 UTC, Kwonkyu approved these changes
죠습니다~!

2022-01-21 14:39 UTC, buri-1029 requested changes
redis 사용하는 부분에 리뷰 달았어요! 확인해주세요 :)

2022-01-21 14:39 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +					 );
앞부분에 RT 를 붙이신 이유가 궁금합니다. 저는 refresh token 인 것을 구분시키기 위하여 붙였거든요!! 
그리고 하정님의 이메일 인증코드 만료에 대해서는 인증코드가 주이기 때문에 저는 인증코드가 key값으로 들어가고 사용자 이메일이 value값으로 들어가야하지 않을까 생각됩니다.

```suggestion
		redisTemplate.opsForValue()
					 .set(
						"EC:" + code, receiver, EXPIRATION, TimeUnit.MILLISECONDS
					 );
```

2022-01-21 14:39 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
>  	}
이 메서드의 역할은 무엇인가요?

2022-01-22 13:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
> +					 );
아니면 이메일로 구분시키는 것이 맞으니 레디스에서 **EC**로 refresh token(RT)와 구분을 두어서 key값으로 EC + 사용자 이메일로 넣고 value 값으로 인증코드를 관리하는 게 맞는 것 같아용!!

2022-01-23 10:28 UTC, healtheefart commented on src/main/java/com/prgrms/needit/domain/user/email/service/EmailService.java
>  	}
제목에 보이는 6자리 인증코드를 000-000 으로 보여주는 메서드인데 createMessage에서만 쓰이는 로직이니 합쳐도 좋을 것 같습니다! 수정해서 push 하겠슴다!

2022-01-23 10:34 UTC, healtheefart commented
이메일 인증코드 재전송 하는 부분을 유효성 검증 로직(전송/재전송 시에 처음 전송하는 이메일인지, 재전송하는 이메일인지 확인)을 추가하여 나눌까 생각했는데
코드가 대부분이 중복되고(유효성 검증코드도 거의 동일), 전송/재전송을 구분할 필요가 있을까 고민하다가
재전송 로직을 삭제하기로 했습니다!

2022-01-23 13:20 UTC, buri-1029 approved these changes
중복된 코드를 줄이니 깔끔해져서 더 보기 좋은 것 같아요!
private 메서드 부분을 코드 아래 쪽으로 옮기면 어떨까유~??

2022-01-24 13:44 UTC, merged