feat: 쪽지 서비스, 기부 예약 디자인 및 서비스 구현
prgrms-web-devcourse/Team_Givooni_Needit_BE pull request #8
Opened 2021-12-06 08:02 UTC by Kwonkyu

## 작업 내역
### refactor: 엔티티 재설계
- 기존의 `MessageContract.java`는 사용이 불편했기 때문에 쪽지와 기부 예약을 각각 `ChatMessage.java`, `Contract.java`의 클래스로 분리하였음.
- 기존에 식별자와 타입으로 구분하던 엔티티(회원/센터, '기부할래요'/'기부원해요' 등)는 두 엔티티를 모두 참조하고 필요 시 null로 두는 방식으로 변경하여 JPA를 좀 더 활용할 수 있도록 변경.
- 예를 들어 쪽지 클래스인 `ChatMessage.java`에서는 현재 애플리케이션 목적 상 회원과 센터 간 채팅 기능만 요구되고 있기 때문에 쪽지 서비스를 사용하는 두 엔티티를 모두 참조 필드로 추가하고 어느 쪽에서 보낸 쪽지인지 구분하는 필드를 둠.
- 기부 예약을 나타내는 `Contract.java`는 '기부원해요'와 '기부할래요'의 기부 예약으로 좀 더 분리할까 고민했지만 현재는 보류. 

### feat: 쪽지 서비스 구현
- 쪽지는 게시글 식별자, 댓글 식별자를 바탕으로 어떤 게시글 타입의 어떤 댓글인지 먼저 조회한 후 해당 댓글을 참조하는 쪽지 엔티티의 목록을 100개씩, 필요 시 커서 기반 페이징을 사용하여 탐색하는 방식으로 구현.
- 쪽지 전송 시에도 댓글까지 조회한 후 보내는 이의 타입(인증 토큰의 subject나 principal에서 추출)을 포함하여 쪽지 생성.

### feat: 기부 예약 서비스 구현
- '기부할래요', '기부원해요' 게시글에 달린 댓글에서 시작된 채팅을 나누다가 예약 일정을 잡는 경우 별도의 API에서 예약을 생성하고 자동으로 이 예약을 참조하는 쪽지 메시지를 생성하는 식으로 구현.
- 그럼 프론트엔드에서는 쪽지 목록을 새로고침하거나 예약 API의 응답 데이터로 쪽지를 렌더링할 수 있을 것.
- 웹소켓이 아직 적용되지 않았기 때문에 보낸 쪽에서 쪽지를 그리더라도 반대쪽에서는 모름.

## 특이 사항
현재는 회원(또는 센터)이 생성한 예약을 센터(또는 회원)만, 즉 받는 쪽에서만 수락하거나 거절할 수 있도록 제한하는 등 별도의 인증, 인가 처리가 구현되어 있지 않음. 추후 기본적인 기능 개발이 완료되면 핸들러 인터셉터를 활용하거나 별도의 서비스로 관점을 분리하여 구현 예정.

## 고민 사항
웹 소켓을..
1. 회원이 올린 게시글에 센터가 댓글을 작성.
2. 회원 측에서 확인하고 댓글을 통해 대화창 입장. <- 이 시점에서 웹소켓 접속.
3. 센터에게 쪽지를 보내기 위해 센터가 subscribe 할 링크에 쪽지를 publish.
3. 센터는 접속 후 밀린 쪽지를 받아보고 3번에서 회원이 publish 하는 쪽지도 받음. 그러면 이 센터가 subscribe 하는 링크를 어떻게 생성할 것인가?
4. 센터가 회원에게 보내는 것도 동일하게 회원이 subscribe 하는 링크에 센터가 publish 해야 함. 역시 이 회원이 subscribe 하는 링크를 어떻게 생성할 것인가?
5. 이 회원, 센터 말고 다른 사용자가 이 링크에 subscribe 해서 메시지를 엿듣는 문제가 발생할 수 있지 않을까?  해결 방법은?

데이터베이스 레코드에 회원과 센터의 고유 subscribe URL을 두는 방식이 좋을까? 아니면 subscribe 하는 시점에 인가를 적용할 수 있나? 조사해 볼 것.

2021-12-06 10:51 UTC, buri-1029 requested changes
권규님 저희 끝까지 파이팅해봅시다!

- 파라미터에 long 타입으로 정의하셨는데 기본으로(BaseEntity) id 타입을 Long 타입으로 정의했자나요 그래서 전 형변환없이 모든 id 타입을 Long으로 가져갔으면 좋겠어요! 
- 중간에 타입을 없애는 방식으로 구현하셨는데 제가 지금 전체적으로 보니 그렇게하면 작성해야하는 API도 많아지고 중복코드도 많아진 것 같아요🤔 이부분에 대해서 더 이야기해봅시댜
- 예외같은 경우는 ErrorCode를 이용해서 에러 코드와 예외 메세지를 관리하고 CustomException을 활용하여 통일감있게 갔으면 좋겠어요....😅

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
>  	INVALID_INPUT_VALUE(400, "C002", "올바른 입력 형식이 아닙니다.");
기부 예약 관련 예외면 아래로 구분하여 따로 두면 될 것 같아요! 
위 C001, C002 는 공통으로 생길 수 있는 부분이고 기부 예약과 관련된 알파벳으로 정의해주세요 :)
```suggestion
        INTERNAL_SERVER_ERROR(500, "C001", "정의되지 않은 에러가 발생했습니다."),
        INVALID_INPUT_VALUE(400, "C002", "올바른 입력 형식이 아닙니다."),
        
	NOT_FOUND_CONTRACT(404, "???", "해당 기부 예약을 찾을 수 없습니다."); // message source 적용?
```

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +		long donationCommentId
기본 id 타입을 Long Wrapper 타입으로 했으니 형변환하지 않도록 그대로 Long Wrapper 타입으로 적용하면 더 좋을 것 같아요!

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +		}
예외 처리하는 부분을 맞췄으면 하는데요.. 관련 예외 메세지는 ErrorCode로 관리하고 일어날 수 예외는 커스텀으로 처리해서 ErrorCode로 받도록이요!

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +public class EntityFinder {
서비스 단에서 처리안하고 따로 클래스를 만들어서 관리하는 이유는 무엇인가요? 그리고 기부글 댓글과 기부요청 댓글 부분은 제가 담당하는 부분인데 권규님 쪽에서 필요해서 코드를 작성하신건가용? 👀 ??

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	@GetMapping("/donation/{donationId}/{contractId}")
```suggestion
	@GetMapping("/{contractId}/donation/{donationId}")
```
관련 리소스 뒤에 해당 아이디를 붙이는게 RESTful 한 것 같아요!

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
받는 파라미터를 수락, 거절 이라는 타입을 추가해서 하나의 API로 수정할 수 있을 것 같아요

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/bind/ContractRequest.java
> +@Setter
전 전체적으로 `@Setter`를 지양하기 위해 완전 생성자를 사용했습니다 :)

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
일정을 등록하고 조회하는 포맷은 같을 것 같은데 기부글, 기부요청글에 대한 예약을 조회하고 등록하는 부분을 왜 분리한지 궁금합니다! 중간에 구별해주는 타입을 두면 API 하나로 될 것 같은데 그 타입을 두는 것이 싫어서 이와 같이 분리한건가요? 

(타입으로 구별하지 않는 방법을 사용하니 API가 늘어나는 군요....흠 이부분에 대해서 내일 오프라인 때 이야기해보면 좋을 것 같아요!)

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/entity/response/DonationContractResponse.java
> +	}
PR 내용에서 
`기존에 식별자와 타입으로 구분하던 엔티티(회원/센터, '기부할래요'/'기부원해요' 등)는 두 엔티티를 모두 참조하고 필요 시 null로 두는 방식으로 변경하여 JPA를 좀 더 활용할 수 있도록 변경.` 이 부분이 요 부분인가요? 내일 오프라인 때 설명해주세영😆

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/controller/bind/ChatMessageRequest.java
> +	// 채팅 텍스트.
주석은 나중에 최종 배포할때는 제거하면 좋겠어유!

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
여기두..

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
중간에 구별해주는 타입을 사용하지 않으면 이와 같이 코드가 중복될 것 같아요!
아니면 지금 코드에서 중복을 없앨 수 있는 방법이 있는지 생각해보도록 해용🤔

2021-12-06 10:51 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/exception/ContractNotFoundException.java
> +
공통에 있는 CustomException의 ErrorCode를 받아 예외를 관리하는 것처럼 전체적으로 통일감을 가졌으면 좋겠어요🤔

2021-12-06 12:02 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
>  	INVALID_INPUT_VALUE(400, "C002", "올바른 입력 형식이 아닙니다.");
원래는 Contract의 C로 하려고 했는데 이미 있어서.. 코드를 뭘로 할 지 고민 좀 해볼게요!

2021-12-06 12:05 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +		long donationCommentId
엔티티의 id 타입은 영속되지 않았을 때를 생각해서 null로 둘 수 있는 `Long` 타입인 거지 영속된 엔티티를 조회하기 위한 id 파라미터가 null일 이유는 없고 그래서도 안 된다고 생각해요. 스프링 데이터 리포지토리의 find 메서드도 null을 받으면 예외를 던지기 때문에 그 가능성을 둘 이유는 없어보입니다.

2021-12-06 12:06 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +		}
원래 저 부분은 '기부할래요', '기부원해요' 게시글의 댓글 쪽 예외라 안 건드리고 임시적으로 `IllegalArgumentException` 으로 조치해두었습니다! 나중에 관련 예외로 변경하겠습니다

2021-12-06 12:07 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +public class EntityFinder {
앗 맞아요 ㅋㅋㅋ 추후 삭제 예정입니다

2021-12-06 12:08 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	@GetMapping("/donation/{donationId}/{contractId}")
뭔가 contract에 속한 donation 을 다루는 것처럼 느껴지진 않을까요?

2021-12-06 12:11 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
음 그러네요 수정하겠습니다!

2021-12-06 12:12 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/bind/ContractRequest.java
> +@Setter
커맨드 객체는 습관적으로 getter, setter를 붙이게 되네요. 반영하겠습니다.

2021-12-06 12:16 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
타입에 대한 검증도 필요하고 컨트롤러에서 타입에 따라 서비스 메서드를 호출하는 로직이 들어가는걸 지양하고자 위처럼 분리했네요. '기부할래요' 와 '기부원해요' 의 예약 결과값도 포함하고 있는 게시글의 식별자가 달라서 같은 응답 클래스에 둘 중 하나를 null로 두고 포함하기보다 분리하는 방법을 택했습니다.

2021-12-06 12:20 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/entity/response/DonationContractResponse.java
> +	}
넹 로직 상으로는 기부할래요 예약(`contract`)에 기부할래요 게시글(`donation`) 가 null 이면 안되지만 NPE 때문에 한 번 검증했네요.

2021-12-06 12:21 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/controller/bind/ChatMessageRequest.java
> +	// 채팅 텍스트.
앗 깜빡했네요! 바로 삭제하겠습니다

2021-12-06 12:22 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
아 서비스 메서드에 주석은 나중에 헷갈릴까봐 일부러 달아놓았어요!

2021-12-06 12:23 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
어떤 부분에서 중복이 있을까요?

2021-12-06 12:24 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/contract/exception/ContractNotFoundException.java
> +
아하 저건 확인 못했네요. 반영하겠습니다

2021-12-06 15:44 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/utils/EntityFinder.java
> +		long donationCommentId
[참고 블로그](https://junhyunny.github.io/java/auto-boxing-performance-test/)
long 타입일때 0이라는 값이 들어오면 값이 없는 null인 건지 0이라는 값인 건지 구분하기 어렵기때문에 파라미터도 Long을 사용할 수 있다고 생각해요.

2021-12-06 15:50 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	@GetMapping("/donation/{donationId}/{contractId}")
그럼 API 설계에 대해서 다시 고민해봐야 할 것 같아영 위 API처럼 작성하면 restful 하지 않다는 것으로 알고있거든용 [참고](https://eblo.tistory.com/44)

2021-12-06 15:52 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/controller/ContractController.java
> +	}
저는 DonationContractResponse, WishContractResponse 이 두 부분의 차이만 있고 전체적으로 중복된 코드처럼 보여서요! 이부분을 해결해서 API 하나로 합쳐도 좋을 것 같아용

2021-12-06 15:53 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
앗 주석이 아니라 아래와 같이 중복된 코드같다는 부분이에옹

2021-12-06 15:54 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/service/ChatMessageService.java
> +	}
여기서도 보면 DonationComment, DonationWishComment의 차이만 있을 뿐 나머지 로직은 다 같아보입니닷

2021-12-08 04:20 UTC, buri-1029 requested changes
권규님 항상 파이팅이에오!!
권규님 코드에 저의 생각을 남겨보았어요...!! 
답글이나 미팅에서 같이 이야기해봐영

2021-12-08 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_SUPPORTED_STATUS(HttpStatus.BAD_REQUEST.value(), "G002", "적용할 수 없는 예약 상태입니다.");
공통으로 사용하는 부분에서 수정이 있다면 슬랙으로 통해 변경사항을 알려주거나 팀원들과 이야기 후 수정했으면 좋겠어유😅

2021-12-08 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/exception/CustomException.java
> +	private final ErrorCode errorCode;
이 부분도 `final`을 추가하는 것을 원하면 다른 CustomException의 코드도 변경해야하니 슬랙으로도 변경내용을 남겨주세용 :)

2021-12-08 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/contract/exception/ContractNotFoundException.java
> +}
오홍 CustomException을 상속받으면 되겠네용 굳굳

2021-12-08 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/entity/ChatMessage.java
> +	private DonationWishComment donationWishComment;
쪽지를 저장하는 도메인인가요? comment가 아닌 어떤 기부글에서 나온 쪽지인지 알아야할 것 같은데여??
댓글 도메인과 연관 관계를 가질 필요 없는 것 같아용🤔 👀

2021-12-08 04:20 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/message/entity/ChatMessage.java
> +public class ChatMessage extends BaseEntity {
권규님은 중간에 타입을 두기 꺼려하셔서 ChatMessage, Contract로 구분하셨는데 저는 둘을 합치고 이 쪽지의 내용이 일정인지 메세지인지 구별해주는 타입만 넣으면 전체적인 코드가 깔끔해질 것 같은데 권규님은 어떻게 생각하세용?

2021-12-09 07:32 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_SUPPORTED_STATUS(HttpStatus.BAD_REQUEST.value(), "G002", "적용할 수 없는 예약 상태입니다.");
😭 😭 😭

2021-12-09 07:33 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/entity/ChatMessage.java
> +	private DonationWishComment donationWishComment;
수정 완료~!

2021-12-09 07:41 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/message/entity/ChatMessage.java
> +public class ChatMessage extends BaseEntity {
저는 그래도 채팅 메시지와 기부 예약은 서로 다른 개념이라고 생각해서 별도의 클래스로 분리했어요! 그래서 지금 코드가 조금 번거로워지더라도 나중에 기능 구현이나 아니면 기능 자체의 의미(기부 도메인을 다루는데 채팅 메시지 도메인이 영향을 받는다)를 좀 더 분리하기 위해서 별도의 클래스로 두었습니다.

추후 코드 퀄리티를 보고 다시 한 번 고려해보겠습니당!

2021-12-09 08:51 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/exception/CustomException.java
> +	private final ErrorCode errorCode;
ㅠㅠㅠㅠㅠㅠ죄송합니다!

2021-12-12 15:47 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_FOUND_DONATION_WISH(404, "W002", "존재하지 않는 기부희망글입니다."),
이부분은 기부글과 함께 D로 해놓은거였는데 권규님이 다시 수정한건가요....?

2021-12-12 15:48 UTC, buri-1029 commented on src/main/java/com/prgrms/needit/domain/board/donation/entity/DonationComment.java
> +		donation.getComments().add(this);
이부분은 제가 addComment 메서드로 빼놨습니다..!!

2021-12-12 15:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/common/error/ErrorCode.java
> +	NOT_FOUND_DONATION_WISH(404, "W002", "존재하지 않는 기부희망글입니다."),
엌 아까 컨플릭트 해결하다가 헷갈렸나봐유

2021-12-12 15:49 UTC, Kwonkyu commented on src/main/java/com/prgrms/needit/domain/board/donation/entity/DonationComment.java
> +		donation.getComments().add(this);
좋아요!!

2021-12-12 15:54 UTC, buri-1029 approved these changes

2021-12-12 15:56 UTC, merged